version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "5000:5000" # match Vite port if changed
    volumes:
      - ./client:/app
      - /app/node_modules  # avoid overwriting node_modules
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true  # important for file watching in Docker
    command: npm run dev

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

  api:
    build:
      shm_size: '2gb'
      context: ./api
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - FLASK_ENV=development